import React from "react";
const Consts = {
  
  ProfileStep : 'Add Profile Photo',
  Gallery:"Gallery",
  skip:"SKIP",
  login:"Login",
  signup:"Sign Up",
  email:"Email",
  password:"Password",
  rememberMe:"Remember Me",
  forgotPass:"Forgot Password?",
  or:"OR",
  loginWith:"Login With",
  name:"Name",
  confirmPass:"Confirm Password",
  washFold:"Wash & Fold",
  dryClean:"Dry Clean & Wash",
  premiumwash:"Premium Wash",
  washIron:"Wash & Iron",
  dryClean:"Dry Clean & Wash",
  loremipsum:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur varius ipsum vel augue dictum viverra. Morbi sed erat tortor. Aliquam est purus,",
  home:'Home',
  myservice:'My Service',
  notification:'Notification',
  myaccount:'My Account',
  servieWash:'Services on Wash',
  getStarted:'Get Started',
}
export default Consts;